#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
pt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend thelhatri.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 441038-web-01 34.203.29.130:80
        server 441038-web-02 54.236.30.130:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
